source 'https://github.com/CocoaPods/Specs.git'

project 'DemoPod.xcodeproj'
platform :ios, '14.0'

use_frameworks!

target 'Demo' do

pod 'SkyPath'

end

post_install do |installer|
installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        new_xcconfig = xcconfig.sub('OTHER_LDFLAGS = $(inherited) -ObjC', 'OTHER_LDFLAGS = $(inherited)')
        File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
    end
  end
end